extend = [{ path = "./x86_64/Makefile.toml" }, { path = "./third-party/Makefile.toml"}]

[env]
TARGET_DIR = "target"

[env.development]
PROFILE = "dev"
PROFILE_DIR = "debug"

[env.release]
PROFILE = "release"
PROFILE_DIR = "release"

[tasks.init]
command = "mkdir"
args = ["-p", "target"]

[tasks.default]
clear = true
command = "echo"
args = ["You forgot to pick a build action. No default set."]

[tasks.legacy-migration]
disabled = true

[tasks.run]
clear = true
dependencies = [ "third_party" ]
script_runner = "@duckscript"
script = '''
    cm_run_task run_${1}
'''

[tasks.build]
clear = true
dependencies = [ "third_party" ]
script_runner = "@duckscript"
script = '''
    cm_run_task build_${1}
'''

[tasks.check]
clear = true
dependencies = [ "third_party" ]
script_runner = "@duckscript"
script = '''
    cm_run_task check_${1}
'''

[tasks.clean]
clear = true
dependencies = [ "clean_common", "clean_x86_64" ]

[tasks.clean_common]
command = "cargo"
cwd = "common"
args = ["clean"]

[tasks.clean_x86_64]
command = "cargo"
cwd = "x86_64"
args = ["clean"]