[tasks.build_x86_64]
toolchain = "nightly"
dependencies = [ "build_multiboot2" ]

[tasks.check_x86_64]
toolchain = "nightly"
dependencies = [ "check_multiboot2" ]

[tasks.build_multiboot2]
toolchain = "nightly"
command = "cargo"
cwd = "x86"
args = ["build", "-p", "multiboot2_loader", "--profile", "${PROFILE}"]

[tasks.check_multiboot2]
toolchain = "nightly"
command = "cargo"
cwd = "x86"
args = ["check", "-p", "multiboot2_loader", "--profile", "${PROFILE}"]