[env]
X86_64_LIMINE_LOC = "x86_64/target/x86_64-unknown-none/${PROFILE}/x86_64_limine"

[tasks.run_x86_64]
toolchain = "nightly"
dependencies = [ "build_x86_64_limine" ]

[tasks.build_x86_64]
toolchain = "nightly"
dependencies = [ "build_x86_64_limine" ]

[tasks.check_x86_64]
toolchain = "nightly"
dependencies = [ "check_x86_64_limine" ]

[tasks.build_x86_64_limine]
toolchain = "nightly"
command = "cargo"
cwd = "x86_64"
args = ["build", "--profile", "${PROFILE}", "--target", "x86_64-unknown-none", "--package", "x86_64_limine"]

[tasks.check_x86_64_limine]
toolchain = "nightly"
command = "cargo"
cwd = "x86_64"
args = ["check", "--profile", "${PROFILE}", "--target", "x86_64-unknown-none", "--package", "x86_64_limine"]