package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "kos-memory",
    srcs = glob(["src/**"]),
    deps = [
        "@crate_index//:talc"
    ]
)
